### ISSUE TITLE
integer check and float check.

### ISSUE THREAD

**Issue by lwilletts** [dylanaraps/pure-sh-bible#2]
Hey, so sometimes I like to check if numbers are integers or floats in sh. For integers this works nicely for me and could be added under the arithmetic section:

```
intCheck() {
    test "$1" -ne 0 2>/dev/null
    test "$?" -ne 2 || return 1
}
```

However, I have yet to work out a nice way of checking for a floating number without calling `bc` up. Wondering what your ideas were.

**Comment by dylanaraps** [comment]
I came up with this after some quick tinkering.

```sh
is_float() {
    case $1 in
        # Contains more than one (or no) decimal places.
        # Contains any non-numerical characters.
        *.*.*|*[!.0-9]*)
            return 1
        ;;

        # Contains a single '.' with leading numerical characters.
        # Is a float.
        *.[0-9]*)
            return 0
        ;;

        # Catch all non-float.
        *)
            return 1
        ;;
    esac
}
```

Comments added to explain what's going on and the code is expanded for clarity. Returns `0` for floats and `1` for non-floats.

Correctly passes the following tests:

```sh
is_float 0.223
is_float .223
is_float 1.
is_float
is_float .
is_float 1.000a
is_float a.b.c
is_float 1.test
is_float test.1
is_float test
is_float 1.1
is_float 1
is_float 20.0001
is_float 1.1.1
```

I could be wrong in my interpretation of what a valid float is, I'd love to hear your thoughts.

**Comment by dylanaraps** [comment]
A condensed version looks like this:

```sh
is_float() {
    case $1 in
        *.*.*|*[!.0-9]*) ;;
        *.[0-9]*) return 0
    esac

    return 1
}
```

**Comment by lwilletts** [comment]
Not sure if `.223` should be counted as a float or not. Good solution though.

**Comment by dylanaraps** [comment]
That's an easy change:

```sh
is_float() {
    case $1 in
        *.*.*|*[!-.0-9]*) ;;
        *[0-9].[0-9]*) return 0
    esac

    return 1
}
```

**Comment by lwilletts** [comment]
Looks good to me.

**Comment by dylanaraps** [comment]
Added to the bible. :+1:

**Comment by dylanaraps** [comment]
Here's an integer check too:

```sh
is_int() {
    case $1 in
        *[!-0-9]*|'') return 1 ;;
        *[0-9]*)
    esac
}
```
