### ISSUE TITLE
"stty size" POSIX

### ISSUE THREAD

**Issue by ricardoG08** [dylanaraps/pure-sh-bible#26]
Hi Dylan, out of curiosity, haven't you found a POSIX way to get the size of the terminal?

**Comment by cmplstofB** [comment]
`$COLUMNS` and `$LINES`?

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03

**Comment by ricardoG08** [comment]
I'm all dumb, I didn't look at the variables 😔, excuse me, I'm learning to program in shell with "sh" following the POSIX standard, a few days ago I finished programming a password manager inspired by "pash", but my programming is not so good like Dylan's:

https://git.disroot.org/ricardog08/passgesh

Thank you very much for your answer.

**Comment by dylanaraps** [comment]
`stty size` *is* POSIX (very recent). See https://austingroupbugs.net/view.php?id=1053 and https://austingroupbugs.net/view.php?id=1151

**Comment by cmplstofB** [comment]
Oh, I didn’t know that (`stty size`).
Thank you for telling!

**Comment by ricardoG08** [comment]
Thanks Dylan

**Comment by ricardoG08** [comment]
Thanks Dylan

**Comment by ricardoG08** [comment]
Thanks Dylan
